name: Tests
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  standard_tests:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    env:
      BOUT_TEST_TIMEOUT: "5m"
      PETSC_DIR: /usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real
      PETSC_ARCH: ""
      SLEPC_DIR: /usr/lib/slepcdir/3.7.4/x86_64-linux-gnu-real
      SLEPC_ARCH: ""
      OMP_NUM_THREADS: ${{ matrix.config.omp_num_threads }}
      PYTHONPATH: ${{ github.workspace }}/tools/pylib
      OMPI_MCA_rmaps_base_oversubscribe: yes
      MPIRUN: mpiexec -np
    strategy:
      fail-fast: false
      matrix:
        # Need this to be able to exclude the coverage job
        is_master_or_next:
          - ${{ github.ref ==  'refs/heads/master' || github.ref == 'refs/heads/next'  || github.base_ref ==  'master' || github.base_ref == 'next' }}
        config:
          - name: "Debug, shared"
            os: ubuntu-18.04
            configure_options: "--enable-shared
                                --enable-sigfpe
                                --enable-debug
                                --enable-track
                                --with-hdf5
                                --with-petsc
                                --with-slepc
                                --with-sundials=/home/runner/local"
            script_flags: "-uim"

          - name: "Debug, shared, explictly 1 thread"
            os: ubuntu-18.04
            configure_options: "--enable-shared
                                --enable-sigfpe
                                --enable-debug
                                --enable-track
                                --with-hdf5
                                --with-petsc
                                --with-slepc
                                --with-sundials=/home/runner/local"
            script_flags: "-uim"
            omp_num_threads: 1

          - name: "CMake, shared, debug, Ubuntu 20.04"
            os: ubuntu-20.04
            cmake_options: "-DBUILD_SHARED_LIBS=ON
                            -DBOUT_USE_PETSC=ON
                            -DBOUT_USE_SLEPC=ON
                            -DBOUT_USE_HDF5=ON
                            -DBOUT_USE_SUNDIALS=ON
                            -DSUNDIALS_ROOT=/home/runner/local
                            -DCMAKE_BUILD_TYPE=Debug"
            omp_num_threads: 1

        exclude:
          # Don't run the coverage tests if the branch isn't master or next
          - is_master_or_next: false
            config:
              name: "Coverage"

    steps:
      - name: Job information
        run: |
          echo Build: ${{ matrix.config.name }}, ${{ matrix.config.os }}
          echo Configure options: ${{ matrix.config.configure_options }}
          echo CMake options: ${{ matrix.config.cmake_options }}

      - name: Install dependencies
        run: sudo apt update &&
             sudo apt install -y
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdf-c++4-dev
                 netcdf-bin
                 hdf5-tools
                 python3
                 python3-pip
                 python3-pytest
                 python3-numpy
                 python3-scipy
                 lcov
                 libhdf5-mpi-dev
                 openmpi-bin
                 libopenmpi-dev
                 petsc-dev
                 slepc-dev
                 liblapack-dev
                 libparpack2-dev

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install pip packages
        run: |
          ./.pip_install_for_travis.sh 'cython~=0.29' 'netcdf4~=1.5' 'sympy~=1.5' 'gcovr' 'cmake' 'h5py'
          # Add the pip install location to the runner's PATH
          echo ~/.local/bin >> $GITHUB_PATH

      - name: Cache SUNDIALS build
        uses: actions/cache@v2
        with:
          path: /home/runner/local
          key: bout-sundials-${{ matrix.config.os }}

      - name: Build SUNDIALS
        run: ./.build_sundials_for_travis.sh

      - name: Build (configure)
        if: ${{ ! contains(matrix.config.name, 'CMake') }}
        run: ./.travis_script.sh ${{ matrix.config.script_flags }}
        env:
          LD_LIBRARY_PATH: /home/runner/local/lib:$LD_LIBRARY_PATH
          CONFIGURE_OPTIONS: ${{ matrix.config.configure_options }}

      - name: Build (CMake)
        if: ${{ contains(matrix.config.name, 'CMake') }}
        run: |
          cmake --version
          cmake . -B build ${{ matrix.config.cmake_options }}
          cmake --build build --target build-check -j 2
          cd build
          ctest --output-on-failure --timeout 300

